### ISSUE TITLE
[FEATURE REQUEST] wildcard domain on Ingress Operator - use case

### ISSUE THREAD

**Issue by ionutz89** [openfaas/ingress-operator#45]
It will be useful if we can pass on the ingress operator the `secretName` on `config.yaml`.

At the moment it only creates a new cert from cert issuer like the `cert-manager` provider.

We have a case where we are using only wildcard domain and we have to edit manually each Ingress to use the same `secretName` like an example below.

```
apiVersion: openfaas.com/v1alpha2
kind: FunctionIngress
metadata:
  name: nodeinfo
  namespace: openfaas
spec:
  domain: "nodeinfo.myfaas.club"
  function: "nodeinfo"
  ingressType: "nginx"
  tls:
     enabled: true
     secretName: same-cert-secret
```
    
If it is a workaround like to automate this bit, it will very useful to know.

What do you think about it?
