### ISSUE TITLE
Function not invokable at specified path; returns 404 (nginx)

### ISSUE THREAD

**Issue by HighCrit** [openfaas/ingress-operator#48]
## Expected Behaviour
The function deployed in the steps below should be invokable at `http://example.kube/api/v1/test/`.

## Current Behaviour
The function deployed is not reachable at `http://example.kube/api/v1/test/` but rather a 404 (by Nginx) is returned. Visiting `http://example.kube/api/v1/test/(.*)` also returns a 404 (OpenFaaS). While the function works as intended at `http://gw.example.kube/function/test-fn`

## Are you a GitHub Sponsor (Yes/No?)

Check at: https://github.com/sponsors/openfaas
- [ ] Yes
- [x] No

## List All Possible Solutions and Workarounds
The only workarounds I can think of right now. Are to either call the gateway path (i.e., not using the ingress-operator) or manually compose and maintain ingresses.

## Which Solution Do You Recommend?

I'd prefer it if I got ingress-operators working as intended.

## Steps to Reproduce (for bugs)

1. Start with a clean kubernetes cluster.
2. Add `127.0.0.1 example.kube` and `127.0.0.1 gw.example.kube` to your hosts file.
3. Execute the following shell script
```sh
GW_HOST="http://gw.example.kube"
FN_NAME="test-fn"

# Create namespaces
kubectl create namespace ingress-nginx
kubectl apply -f https://raw.githubusercontent.com/openfaas/faas-netes/master/namespaces.yml

# Update chart repos
helm repo add nginx-stable https://helm.nginx.com/stable
helm repo add openfaas https://openfaas.github.io/faas-netes/

helm repo update

# Apply charts
helm install example-ingress nginx-stable/nginx-ingress \
    -n ingress-nginx \
    --set rbac.create=true

helm install openfaas openfaas/openfaas \
    -n openfaas  \
    --values openfaas.yml

# Wait for OpenFaaS to start
sleep 60

# Login to gateway
echo $(kubectl -n openfaas get secret basic-auth -o jsonpath="{.data.basic-auth-password}" | base64 --decode) | faas-cli login -g $GW_HOST -u admin --password-stdin

# Get and host base node14 template
faas-cli template store pull node14
faas-cli new $FN_NAME --lang node14 -g $GW_HOST
faas-cli build -f "$FN_NAME.yml"
faas-cli deploy -f "$FN_NAME.yml"

# Apply FunctionIngress for test-fn
kubectl apply -f test-fi.yml
```
with the following files:
```yml
# openfaas.yml
functionNamespace: openfaas-fn
generateBasicAuth: true
ingressOperator:
  create: true
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: gw.example.kube
      serviceName: gateway
      servicePort: 8080
      path: /
faasnetes:
  imagePullPolicy: IfNotPresent

# test-fi.yml
apiVersion: openfaas.com/v1alpha2
kind: FunctionIngress
metadata:
  name: test-fn
  namespace: openfaas
spec:
  domain: "example.kube"
  function: "test-fn"
  ingressType: "nginx"
  path: "/api/v1/test/(.*)"
```
4. Go to `http://example.kube/api/v1/test/`

## Context
I'm trying to create a more REST-like path for my api. As well as, replace existing apis with functions.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
```
  ___                   _____           ____
 / _ \ _ __   ___ _ __ |  ___|_ _  __ _/ ___|
| | | | '_ \ / _ \ '_ \| |_ / _` |/ _` \___ \
| |_| | |_) |  __/ | | |  _| (_| | (_| |___) |
 \___/| .__/ \___|_| |_|_|  \__,_|\__,_|____/
      |_|

CLI:
 commit:  72816d486cf76c3089b915dfb0b66b85cf096634
 version: 0.13.13
```
* Docker version `docker version` (e.g. Docker 17.0.05 ):
20.10.7
* What version and distriubtion of Kubernetes are you using? `kubectl version`
I'm using Docker Desktop's Kubernetes at version 1.21.2
* Operating System and version (e.g. Linux, Windows, MacOS):
Windows 10, kubectl reports that the cluster is running on Linux
* Helm version
3.5.3

**Comment by LucasRoesler** [comment]
@HighCrit and @alexellis  I could not reproduce this. 

I had to modify the instructions a little bit to work in `kind`, but this is the process i used which shows a working function ingress:

--- 


Create the file `cluster.yaml`

```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
  - containerPort: 31112
    hostPort: 8080
    protocol: TCP
```

This configures `kind` to bind the ports `80:80`, `443:443`, and `31112:8080`. Which makes the ingress available on localhost an the gateway available on 8080 (the default cli value).


Now create the cluster

```sh
kind create cluster --config=cluster.yaml
```


Next create the required namespaces

```sh
# Create namespaces
kubectl create namespace ingress-nginx
kubectl apply -f https://raw.githubusercontent.com/openfaas/faas-netes/master/namespaces.yml
```

Then install nginx-ingress using the instructions from `kind` https://kind.sigs.k8s.io/docs/user/ingress/#ingress-nginx

```sh
VERSION=$(curl https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/stable.txt)
kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/${VERSION}/deploy/static/provider/kind/deploy.yaml
```
> The manifests contains kind specific patches to forward the hostPorts to the ingress controller, set taint tolerations and schedule it to the custom labelled node.


Now we can install openfaas, 

first create the file `openfaas.yaml`

```yaml
# openfaas.yaml
functionNamespace: openfaas-fn
generateBasicAuth: true
ingressOperator:
  create: true
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: gw.example.kube
      serviceName: gateway
      servicePort: 8080
      path: /
faasnetes:
  imagePullPolicy: IfNotPresent
```
and then run

```sh
helm repo add openfaas https://openfaas.github.io/faas-netes/
helm repo update

helm install openfaas openfaas/openfaas \
    -n openfaas  \
    --values openfaas.yaml
```

Wait for the gateway to startup 

```sh
kubectl wait --namespace openfaas \
  --for=condition=ready pod \
  --selector=app=gateway \
  --timeout=90s
```


Now we can authenticate the CLI

```sh
echo $(kubectl -n openfaas get secret basic-auth -o jsonpath="{.data.basic-auth-password}" | base64 --decode) | faas-cli login -u admin --password-stdin
```

Deploy a test function 

```sh
faas-cli store deploy nodeinfo
```

Wait a moment and then verify the function is running by using 

```sh
faas-cli invoke nodeinfo
```

We can now create the FunctionIngress

```yaml
apiVersion: openfaas.com/v1alpha2
kind: FunctionIngress
metadata:
  name: test-fn
  namespace: openfaas
spec:
  domain: "example.kube"
  function: "nodeinfo"
  ingressType: "nginx"
  path: "/api/v1/test/(.*)"

```

Apply the FunctionIngress

```sh
kubectl apply -f test-fi.yml
```

Wait a moment and test the ingress is working 

```sh
$ curl -v http://example.kube/api/v1/test/
*   Trying 127.0.0.1:80...
* TCP_NODELAY set
* Connected to example.kube (127.0.0.1) port 80 (#0)
> GET /api/v1/test/ HTTP/1.1
> Host: example.kube
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Date: Sat, 10 Jul 2021 14:17:28 GMT
< Content-Type: text/plain; charset=utf-8
< Content-Length: 105
< Connection: keep-alive
< Etag: W/"69-hQd9Fsiq+ZlCoMo3qufaUyrnJ44"
< X-Call-Id: 535b3b84-b71d-4b78-94b8-f11f83c400d2
< X-Duration-Seconds: 0.021057
< X-Start-Time: 1625926647979244691
< 
Hostname: nodeinfo-7547c56bbb-zdj2f

Arch: x64
CPUs: 8
Total mem: 15702MB
Platform: linux
Uptime: 107548
* Connection #0 to host example.kube left intact
```

You can see it in the nginx access logs

```sh
$ kubectl -n ingress-nginx logs deploy/ingress-nginx-controller
// truncated
172.27.0.1 - - [10/Jul/2021:14:06:13 +0000] "GET /api/v1/test/ HTTP/1.1" 200 105 "-" "curl/7.68.0" 88 0.025 [openfaas-gateway-8080] [] 10.244.0.11:8080 105 0.024 200 cde4d1118c0d49df78b81fd8dc2ae0fd
172.27.0.1 - - [10/Jul/2021:14:17:28 +0000] "GET /api/v1/test/ HTTP/1.1" 200 105 "-" "curl/7.68.0" 88 0.031 [openfaas-gateway-8080] [] 10.244.0.11:8080 105 0.032 200 473f95b3949a3fc102fdfe29d5e4e06d
```
---

I made two important changes to the instructions

1. i change the cluster config so that the required ports were immediately bound to localhost
2. i did not use the nginx-ingress helm chart. I tried this several times but it had various issues even starting. Once i switched to the install manifest prepared by the `kind` team, it started working immediately. 
---

I think this shows that  the reported issue is mostly a configuration problem in the cluster or nginx-ingress. 

@HighCrit  Getting the logs directly from nginx-ingress-controller would be very helpful to further debug the problem.
