### ISSUE TITLE
How do I get the full path for a REST-style function?

### ISSUE THREAD

**Issue by harichards** [openfaas/ingress-operator#55]
If I have created a function ingress resource like so:

```yaml
apiVersion: openfaas.com/v1alpha2
kind: FunctionIngress
metadata:
  name: pets
  namespace: openfaas
spec:
  domain: api.petstore.com
  function: pets
  ingressType: nginx
  path: /pets/(.*)
```

How would I retrieve the `(.*)` part of the path from within the function handler? I am using the `golang-http` template btw.

**Comment by alexellis** [comment]
Hi @harichards you'll need to fill out the whole issue template here including all steps to reproduce your setup. I would suggest you create a public GitHub repo.

https://raw.githubusercontent.com/openfaas/ingress-operator/master/.github/ISSUE_TEMPLATE.md

Alex

**Comment by harichards** [comment]
## Expected Behaviour


Given a function using the `golang-middleware` template:
```go
package function

import (
	"fmt"
	"net/http"
)

func Handle(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusOK)
	w.Write([]byte(fmt.Sprintf("Path: %s", r.URL.Path)))
}
```
a function ingress Kubernetes resource:
```yaml
apiVersion: openfaas.com/v1alpha2
kind: FunctionIngress
metadata:
  name: go-fn
  namespace: openfaas
spec:
  domain: api.example.com
  function: go-fn
  ingressType: nginx
  path: /go-fn/(.*)/foo/(.*)/bar
```
and invoking the function handler like so:
```
curl http://api.example.com/go-fn/hello/foo/world/bar
```
expected the following output:
```
Path: /go-fn/hello/foo/world/bar
```
## Current Behaviour


Instead, I get the following output:
```
Path: /hello
```
## Are you a GitHub Sponsor (Yes/No?)


Check at: https://github.com/sponsors/openfaas
- [ ] Yes
- [x] No

## List All Possible Solutions and Workarounds



I don't know why this is happening other than it may have something to do with the communication between Nginx and OpenFaaS, where the HTTP handler function is not receiving the full path as input. Perhaps a closer look at the OpenFaaS ingress operator is required.

## Which Solution Do You Recommend?

Ideally the full path would be present in `r.URL.Path`.

## Steps to Reproduce (for bugs)


Steps are detailed above, see [Expected Behaviour](#expected-behaviour).

## Context


I am trying to map some functions to a REST API. This requires extracting the name of the resource being accessed from the URL path. Sometimes there are multiple resources in a single path, for example:
```
https://api.github.com/repos/{owner}/{repo}/branches/{branch}
```
This path could be mapped to an OpenFaaS function like so:
```yaml
apiVersion: openfaas.com/v1alpha2
kind: FunctionIngress
metadata:
  name: get-branch
  namespace: openfaas
spec:
  domain: api.github.com
  function: get-branch
  ingressType: nginx
  path: /repos/(.*)/(.*)/branches/(.*)
```
I cannot figure out how to access the full path from within the function handler. Therefore, my function does not know which resource to access.
## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
```
CLI:
 commit:  72816d486cf76c3089b915dfb0b66b85cf096634
 version: 0.13.13
```
* Docker version `docker version` (e.g. Docker 17.0.05 ):
```
Client: Docker Engine - Community
 Cloud integration: 1.0.17
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:54:02 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:52:10 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
* What version and distribution of Kubernetes are you using? `kubectl version`
```
Client Version: version.Info
{
    Major: "1",
    Minor: "22",
    GitVersion: "v1.22.1",
    GitCommit: "632ed300f2c34f6d6d15ca4cef3d3c7073412212",
    GitTreeState: "clean",
    BuildDate: "2021-08-19T15:45:37Z",
    GoVersion: "go1.16.7",
    Compiler: "gc",
    Platform: "linux/amd64"
}
Server Version: version.Info
{
    Major:"1",
    Minor:"21+",
    GitVersion:"v1.21.2-eks-0389ca3",
    GitCommit:"8a4e27b9d88142bbdd21b997b532eb6d493df6d2",
    GitTreeState:"clean",
    BuildDate:"2021-07-31T01:34:46Z",
    GoVersion:"go1.16.5",
    Compiler:"gc",
    Platform:"linux/amd64"
}
```
* Operating System and version (e.g. Linux, Windows, MacOS):
WSL2 Linux Ubuntu 20.04


* Link to a code example (gist or repo) to reproduce issue:
Code example is detailed above, see [Expected Behaviour](#expected-behaviour).
