### ISSUE TITLE
Support for watching multiple or all namespaces in ingress-operator

### ISSUE THREAD

**Issue by koss110** [openfaas/ingress-operator#63]
## Expected Behaviour
I expect the ingress-operator to be able to watch multiple namespaces, all namespaces, or namespaces specified by annotation. This would also include the appropriate RBAC permissions for the ingress-operator.

## Current Behaviour
Currently, the ingress-operator is set to watch a specific namespace as defined in the 'function_namespace' and 'ingress_namespace' environment variables. If I want to use a different namespace, I have to manually override these values and adjust the RBAC permissions.

## List All Possible Solutions and Workarounds
Adding an option to watch all namespaces in nothing was set.
Allowing the definition of multiple namespaces to watch.
Allowing the use of namespace annotations to determine which namespaces to watch.

## Which Solution Do You Recommend?
I would recommend implementing the option to watch namespaces by labels(as with OpenFaas pro), as this would offer the most flexibility to users.

## Steps to Reproduce (for bugs)
It's more a feature request than bug.
Anyway the steps to reproduce are simple: deploy the stack.yaml to namespace associated with openfaas.

## Context
I am trying to deploy the ingress-operator in a different namespace ('demo' in my case).
However, I need to override the 'function_namespace', 'ingress_namespace' values and adjust the RBAC permissions time.

## Your Environment
Less related to the issue.

* FaaS-CLI version ( Full output from: `faas-cli version` ):
 commit:  0074051aeb837f5f160ee8736341460468b5c190
 version: 0.15.4
+ pro license.

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* What version and distriubtion of Kubernetes are you using? `kubectl version`
Server Version: v1.21.14-eks-0a21954

* Operating System and version (e.g. Linux, Windows, MacOS):
AmazonLinux2

```
version: 1.0
provider:
  name: openfaas
  gateway: https://openfaas-gw.dev.local/
functions:
  next-gen:
    lang: python@3.11
    handler: .
    image: my-custom-image:tag
    secrets: []
    environment:
      fprocess: python function/main.py
    labels:
      com.openfaas.scale.min: "1"
      com.openfaas.scale.max: "5"
      com.openfaas.scale.target: "5"
      com.openfaas.scale.type: rps
      com.openfaas.scale.target-proporation: "0.80"
function-ingress:
  next-gen-ing:
    domain: "gen2.dev.local"
    function: "next-gen"
    ingressType: "nginx-general"
    annotations:
      external-dns.alpha.kubernetes.io/hostname: "gen2.dev.local"
```

**Comment by alexellis** [comment]
This may be supported already.

The FunctionIngress object is designed to be deployed into the core `openfaas` namespace:

```yaml
apiVersion: openfaas.com/v1
kind: FunctionIngress
metadata:
  name: nodeinfo
  namespace: openfaas
spec:
  domain: "api.example.com"
  function: "nodeinfo"
  ingressType: "nginx"
  path: "/v1/nodeinfo/(.*)"
  tls:
    enabled: true
    issuerRef:
      name: "letsencrypt-staging"
      kind: "Issuer"
```

The thing we may need to do is to change the spec to include the functionNamespace as per:

```diff
apiVersion: openfaas.com/v1
kind: FunctionIngress
metadata:
  name: nodeinfo
  namespace: openfaas
spec:
  domain: "api.example.com"
  function: "nodeinfo"
  functionNamespace: "demo"
  ingressType: "nginx"
  path: "/v1/nodeinfo/(.*)"
  tls:
    enabled: true
    issuerRef:
      name: "letsencrypt-staging"
      kind: "Issuer"
```

I'm not sure, but you could try including the namespace within the `  `function` field.

```yaml
  function: "nodeinfo.demo"
```
