### ISSUE TITLE
Add "namespace" to FunctionIngress spec

### ISSUE THREAD

**Issue by alexellis** [openfaas/ingress-operator#68]
## Current Behaviour

All target functions are assumed to be within the openfaas-fn namespace, and the spec only takes a function as an input:

```yaml
apiVersion: openfaas.com/v1
kind: FunctionIngress
metadata:
  name: nodeinfo
  namespace: openfaas
spec:
  domain: "nodeinfo.myfaas.club"
  function: "nodeinfo"
  ingressType: "nginx"
  path: "/v1/profiles/(.*)"
```

## Expected Behaviour

Add a functionNamespace field into the spec:

```diff
apiVersion: openfaas.com/v1
kind: FunctionIngress
metadata:
  name: nodeinfo
  namespace: openfaas
spec:
  domain: "nodeinfo.myfaas.club"
  function: "nodeinfo"
+ functionNamespace: "staging-fn"
  ingressType: "nginx"
  path: "/v1/profiles/(.*)"
```

If we really want to do things properly and make a breaking change, this could be a `functionRef`:

```yaml
spec:
  domain: "nodeinfo.myfaas.club"
  functionRef:
     name: "nodeinfo"
   namespace: "staging-fn"
```

But I think that might be more work than is warranted for now.

## Who is this for? What company will benefit from the changes?

Kubiya asked for this in #63 

## List All Possible Solutions and Workarounds

All FunctionIngress objects and their eventual Ingress objects must be created in the openfaas namespace since they all point at the gateway.

But that said, the namespace is just appended to the path that comes out on the Ingress:

```
http://gateway.openfaas:8080/function/FUNCTION.NAMESPACE
```
